name: colorful_log
description: A colorful log utils.
version: 0.0.1
homepage: https://github.com/EngrZhou/ColorfulLog

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter